name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Build Essentials
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Run Make
      run: make
